kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sc-claim 
  annotations:
    volume.beta.kubernetes.io/storage-class: default-shared 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
