apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3fs-pv
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany
  flexVolume:
    # FIXME: use the right IP
    driver: "kubernetes.io/s3fs-container.sh"
   
